"""Generate Kubernetes manifests for consolidated MySQL servers.

Produces a PersistentVolumeClaim, Service, and Deployment for 7 MySQL servers
(`mysql-1` through `mysql-7`). Each server hosts 4 state databases for the
28 Indian states defined in `app/state_populations.py`.
"""

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_FILE = PROJECT_ROOT / "k8s" / "mysql.yaml"

NUM_SERVERS = 7


def generate_manifests():
    chunks = [
        "# ====================================================================\n"
        "# GENERATED FILE: 7 Consolidated MySQL servers (Pod + Service + PVC)\n"
        "# Each server hosts 4 state databases (28 Indian states total)\n"
        "# Generated by k8s/generate_mysql_manifests.py\n"
        "# ====================================================================\n"
    ]

    for server_index in range(1, NUM_SERVERS + 1):
        server_name = f"mysql-{server_index}"

        chunk = f"""# --- SQL Server: {server_name} ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-{server_index}
  labels:
    app: mysql
    server: {server_name}
    app.kubernetes.io/component: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: {server_name}
  labels:
    app: mysql
    server: {server_name}
    app.kubernetes.io/component: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
    server: {server_name}
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {server_name}
  labels:
    app: mysql
    server: {server_name}
    app.kubernetes.io/component: mysql
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysql
      server: {server_name}
  template:
    metadata:
      labels:
        app: mysql
        server: {server_name}
        app.kubernetes.io/component: mysql
    spec:
      automountServiceAccountToken: false
      containers:
        - name: mysql
          image: mysql:lts-oracle
          args:
            - --innodb-buffer-pool-size=96M
            - --max-connections=100
            - --innodb-redo-log-capacity=134217728
            - --max-allowed-packet=268435456
            - --net-read-timeout=600
            - --net-write-timeout=600
            - --wait-timeout=28800
          ports:
            - name: mysql
              containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: students_db
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: student-app-secrets
                  key: MYSQL_PASSWORD
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -h 127.0.0.1 -uroot -p"$MYSQL_ROOT_PASSWORD" --silent
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 12
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -h 127.0.0.1 -uroot -p"$MYSQL_ROOT_PASSWORD" --silent
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          resources:
            requests:
              cpu: 60m
              memory: 128Mi
              ephemeral-storage: 256Mi
            limits:
              cpu: 800m
              memory: 896Mi
              ephemeral-storage: 2Gi


      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data-{server_index}
---
"""
        chunks.append(chunk)

    OUTPUT_FILE.write_text("".join(chunks), encoding="utf-8")
    print(f"Successfully generated {NUM_SERVERS} MySQL server manifests in {OUTPUT_FILE}")


if __name__ == "__main__":
    generate_manifests()

