"""Generate Kubernetes manifests for per-state MySQL servers.

Produces a separate PersistentVolumeClaim, Service, and Deployment for each
of the 28 Indian states defined in `app/state_populations.py`. Each state's
SQL server runs independently, avoiding redo-log contention and single-pod
bottlenecks while keeping resource requests lightweight for local/minikube execution.
"""

from pathlib import Path
import sys

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "app"))
from state_populations import STATE_POPULATIONS

OUTPUT_FILE = PROJECT_ROOT / "k8s" / "mysql.yaml"


def generate_manifests():
    chunks = [
        "# ====================================================================\n"
        "# GENERATED FILE: One dedicated MySQL server (Pod + Service + PVC) per Indian state\n"
        "# Generated by k8s/generate_mysql_manifests.py\n"
        "# Total states: 28\n"
        "# ====================================================================\n"
    ]

    for state_code in sorted(STATE_POPULATIONS.keys()):
        state_slug = state_code.replace("_", "-")
        display_name, population = STATE_POPULATIONS[state_code]

        chunk = f"""# --- State: {display_name} ({state_code}) ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-{state_slug}
  labels:
    app: mysql
    state: {state_code}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-{state_slug}
  labels:
    app: mysql
    state: {state_code}
spec:
  type: ClusterIP
  selector:
    app: mysql
    state: {state_code}
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-{state_slug}
  labels:
    app: mysql
    state: {state_code}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysql
      state: {state_code}
  template:
    metadata:
      labels:
        app: mysql
        state: {state_code}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: mysql
          image: mysql:lts-oracle
          args:
            - --innodb-buffer-pool-size=64M
            - --max-connections=50
            - --innodb-redo-log-capacity=134217728
          ports:
            - name: mysql
              containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: students_db
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: student-app-secrets
                  key: MYSQL_PASSWORD
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -h 127.0.0.1 -uroot -p"$MYSQL_ROOT_PASSWORD" --silent
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 12
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -h 127.0.0.1 -uroot -p"$MYSQL_ROOT_PASSWORD" --silent
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          resources:
            requests:
              cpu: 30m
              memory: 120Mi
              ephemeral-storage: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
              ephemeral-storage: 1Gi
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data-{state_slug}
---
"""
        chunks.append(chunk)

    OUTPUT_FILE.write_text("".join(chunks), encoding="utf-8")
    print(f"Successfully generated {len(STATE_POPULATIONS)} state MySQL manifests in {OUTPUT_FILE}")


if __name__ == "__main__":
    generate_manifests()
